### ISSUE TITLE
check for Symbol.for instead of just Symbol

### ISSUE THREAD

**Issue by paulirish** [75lb/feature-detect-es6#5]
see https://github.com/isaacs/node-lru-cache/pull/126

**Comment by 75lb** [comment]
[additional check](https://github.com/75lb/feature-detect-es6/commit/c8f1a83dee4a2e685f66853df99f99e8744120ba#diff-168726dbe96b3ce427e7fedce31bb0bcR128) for `Symbol.for` added and released in v1.4.1, thanks 👍

**Comment by paulirish** [comment]
yeah thank you!!​
