### ISSUE TITLE
Async await

### ISSUE THREAD

**Issue by lorengreenfield** [75lb/feature-detect-es6#6]
Hey @75lb are you open to accepting a PR for testing for Async/Await?

**Comment by 75lb** [comment]
Hi! yes, that plus any other missing feature tests would be good thanks...  👍

**Comment by lorengreenfield** [comment]
Excellent, I'll make a PR or two in the near future.

**Comment by 75lb** [comment]
ok, thanks.. add an `.asyncFunctions()` method which returns true if supported, then add a test to each of the `v4.js`, `v5.js` etc files in [here](https://github.com/75lb/feature-detect-es6/tree/master/test). You'll need to create a `v7.js` test file and use it in the [travis config](https://github.com/75lb/feature-detect-es6/blob/master/.travis.yml) from v7 upward.
