### ISSUE TITLE
implement object rest and spread detection

### ISSUE THREAD

**Issue by lorengreenfield** [75lb/feature-detect-es6#8]
To test for object rest and spread you can do this:

```js
eval(var myOb = {valid: true, valid1: true, valid2: true};
var {valid, ...rest} = myOb;
var output = {valid, ...rest};
``` 

It seems that both rest and spread for objects have been made available at the same time by the browser vendors so far.

I could do a PR for this, but it might need a bit of thought around what's actually being tested and what any new test(s) would be named. The current `spread` test only tests spreading an array as function parameters, so it could be worth it to add an array `rest` test as well as an `object rest` and `object spread`, but then you might want to make an alias for spread to be arraySpread too, or you could just do a breaking change and make spread test all of them.

@75lb Thoughts?

**Comment by 75lb** [comment]
yes, i think we'd need separate functions for each of 

* `objectRest`
  * Example: `var { a, ...rest } = { a: 1, b: 2, c: 3 }`
* `objectSpread`
  * Example
    ```
    var spread = {b: 2, c: 3};
    var obj = {a: 1, ...spread};
    ```
* `iterableRest`
  * Example: `var [a, ...b] = [3, 4, 5]`
* `iterableSpread`
  * Example: `Math.max(...[1, 2, 3]) === 3`
* `restParams`
  * Example
    ```
    function (foo, ...args) {}
    ```

We should repurpose the existing `spread` function to return `true` if both `objectSpread` and `iterableSpread` return true. Likewise, we could introduce a `rest` method which returns `true` if `objectRest` and `iterableRest` return true. 

Regarding the tests which perform the actual feature detection, is it possible to reuse tests from [compat-table](https://github.com/kangax/compat-table)?

Yes, PRs welcome to introduce these new feature tests. Don't worry about breaking changes.

**Comment by 75lb** [comment]
Closing - the library is no longer maintained..
